'use client'

import CloseIcon from '@mui/icons-material/Close'
import { Divider } from '@mui/material'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import Dialog from '@mui/material/Dialog'
import DialogActions from '@mui/material/DialogActions'
import DialogContent from '@mui/material/DialogContent'
import DialogTitle from '@mui/material/DialogTitle'
import IconButton from '@mui/material/IconButton'
import Link from '@mui/material/Link'
import Typography from '@mui/material/Typography'
import {
  GridFooterContainer,
  gridFilteredTopLevelRowCountSelector,
  useGridApiContext,
  useGridSelector
} from '@mui/x-data-grid-pro'
import { useState } from 'react'
import { LastUpdatedInfo } from '@/components/LastUpdatedInfo'
import type { Metadata } from '@/lib/types'

export function Footer({ metadata }: { metadata: Metadata }) {
  const [isDialogOpen, setIsDialogOpen] = useState(false)

  const apiRef = useGridApiContext()
  const totalRowCount = useGridSelector(apiRef, gridFilteredTopLevelRowCountSelector)

  const handleOpenDialog = () => setIsDialogOpen(true)

  const handleCloseDialog = () => setIsDialogOpen(false)

  return (
    <GridFooterContainer
      sx={{
        alignItems: 'center',
        display: 'flex',
        justifyContent: 'space-between',
        pl: 1.25,
        pr: 1,
        py: 1
      }}
    >
      <Typography variant="body2">Total Rows: {totalRowCount.toLocaleString()}</Typography>

      <Button onClick={handleOpenDialog} size="small">
        About
      </Button>

      <Dialog onClose={handleCloseDialog} open={isDialogOpen} maxWidth="sm" fullWidth>
        <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          About Honolulu Arrest Logs
          <IconButton onClick={handleCloseDialog} size="small" aria-label="close">
            <CloseIcon />
          </IconButton>
        </DialogTitle>

        <DialogContent>
          <Box component="section">
            <LastUpdatedInfo metadata={metadata} sx={{ mb: 2, display: 'block' }} />

            <Typography variant="body2" color="text.secondary">
              This data is generated by AI extraction from the most recent two weeks of arrest logs. It has not been
              subject to human review.{' '}
              <Link
                href="https://www.bronsonavila.com/blog/extracting-honolulu-arrest-records-from-pdfs-with-ai"
                target="_blank"
                rel="noopener noreferrer"
              >
                Learn more about how it works
              </Link>
              .
            </Typography>

            <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
              For official records, please visit the{' '}
              <Link
                href="https://www.honolulupd.org/information/arrest-logs/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Honolulu Police Department website
              </Link>
              .
            </Typography>
          </Box>

          <Divider sx={{ my: 2 }} />

          <Box component="section" sx={{ mt: 2 }}>
            <Typography variant="subtitle2">Disclaimer</Typography>

            <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
              An arrest is not a conviction. All individuals are presumed innocent.
            </Typography>

            <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
              Independently maintained by{' '}
              <Link href="https://www.bronsonavila.com" target="_blank" rel="noopener noreferrer">
                Bronson Avila
              </Link>
              . Not affiliated with HPD.
            </Typography>
          </Box>
        </DialogContent>

        <DialogActions>
          <Button onClick={handleCloseDialog}>Close</Button>
        </DialogActions>
      </Dialog>
    </GridFooterContainer>
  )
}
